Repository getgauge/gauge, pull requests merged in 2018-05, with the labels that each got.

#1017 Fixing network connection closed error getgauge/gauge-js#136
  api/lang/diagnostics.go
  validation/validate.go
  validation/validation_test.go
Labels: cla-signed, in progress

#1023 Add functionality to list tags, scenarios,specifications of projects
  cmd/list.go
  cmd/list_test.go
  track/track.go
Labels: cla-signed

#1030 Doesn't copy files if post install fails.
  plugin/install/install.go
Labels: cla-signed, in progress

#1031 #144 [Statistics] Specification should be skipped if all scenarios are skipped
  execution/merge.go
  execution/merge_test.go
Labels: cla-signed, in progress

#1040 Fixing partial step implemented as concept, for step with table parameter
  api/lang/codeAction.go
  api/lang/codeAction_test.go
Labels: cla-signed, in progress

#1054 Replacing dynamic and table param names
  conceptExtractor/conceptExtractor.go
  formatter/formatter.go
  formatter/formatter_test.go
  gauge/step.go
  gauge/step_test.go
Labels: cla-signed, in progress

#1047 2017 to 2018 in copyright
  README.md
Labels: cla-signed, in progress

#1060 Added custom lsp request to get specification dirs.
  api/infoGatherer/specDetails.go
  api/lang/completion_test.go
  api/lang/server.go
Labels: cla-signed, in progress

#1053 reference code lens for concepts, #1052
  api/apiMessageHandler.go
  api/infoGatherer/specDetails.go
  api/infoGatherer/specDetails_test.go
  api/lang/codeLens.go
  api/lang/completionStep.go
  api/lang/completion_test.go
  api/lang/references.go
  api/lang/server.go
Labels: cla-signed, in progress

#1049 spec file exentsion is now case insensitive
  util/fileUtils.go
  util/fileUtils_test.go
Labels: in progress

#1069 Fixed bug to creating .gauge folder in non-gauge project, #1056
  cmd/cmd.go
  cmd/run.go
  cmd/run_test.go
Labels: cla-signed, in progress
