Repository getgauge/gauge, pull requests merged in 2018-08, with the labels that each got.

#1124 gauge.properties write optimization
  cmd/.gitignore
  config/properties.go
  config/properties_test.go
Labels: cla-signed, in progress

#1134 Lsp telemetry message
  api/lang/server.go
  api/lang/telemetry.go
  cmd/cmd.go
  cmd/daemon.go
  cmd/version.go
  track/track.go
Labels: cla-signed, in progress

#1138 add support for step to be across lines, #265
  parser/conceptParser_test.go
  parser/specparser.go
  parser/specparser_test.go
  parser/testdata/dynamic_param_concept.cpt
Labels: cla-signed, in progress, ready

#1150 Remove step execution screenshots and messages from after step hooks
  execution/scenarioExecutor.go
  execution/scenarioExecutor_test.go
  execution/simpleExecution.go
  execution/simpleExecution_test.go
  execution/specExecutor.go
  execution/specExecutor_test.go
  execution/stepExecutor.go
  execution/stepExecutor_test.go
  gauge_messages/spec.pb.go
Labels: cla-signed, ready

#1151 add --no-exit-code flag to run, #1126
  cmd/run.go
  cmd/run_test.go
  execution/execute.go
Labels: cla-signed, ready

#1156 rename: no-exit-code to fail-safe
  cmd/run.go
  cmd/run_test.go
  execution/execute.go
  execution/exitcode.go
Labels: cla-signed, ready
