Repository getgauge/gauge, pull requests merged in 2019-03, with the labels that each got.

#1357 xml-report/#16 Fix report missing data
  plugin/handler.go
Labels: cla-signed, ready for Development

#1361 Retain name of arg while setting arg value
  gauge/arg.go
  gauge/arg_test.go
Labels: cla-signed, ready, ready for Development

#1360 Sets gauge environment variable based on selected env
  env/env.go
  env/env_test.go
Labels: cla-signed, ready, ready for Development

#1365 Customized parallel run via tags
  cmd/cmd.go
  cmd/run.go
  env/env.go
  execution/execute.go
  execution/parallelExecution.go
  filter/filter.go
  filter/specItemFilter.go
  filter/specItemFilter_test.go
  filter/specsFilter.go
  gauge/specCollection.go
  gauge/specification.go
  parser/parse.go
Labels: cla-signed, ready, ready for Development

#1371 Add params from scenario table to lookup. #1330
  parser/convert.go
  parser/specparser_test.go
Labels: cla-signed, ready

#1370 Added flag to set max retries count for failed scenario
  cmd/cmd.go
  cmd/run.go
  execution/execute.go
  execution/specExecutor.go
  execution/specExecutor_test.go
  filter/specItemFilter.go
  filter/specItemFilter_test.go
Labels: cla-signed, ready, ready for Development
